### ISSUE TITLE
Missing humanitarian sector codes

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/IATI-Stats#23]
Humanitarian codes `72011` and `72012` are missing and not being used to calculate humanitarian activities

**Comment by andylolz** [comment]
Good spot – and thanks for the PR!

Just trying to figure out what went wrong here…

Looks like these codes were added in https://github.com/codeforIATI/IATI-Codelists-NonEmbedded/pull/52, which predates this fork. The [source repo has the same bug](https://github.com/IATI/IATI-Stats/blob/86b87d612333b775bd3f2aa9d70e510c608d6333/stats/dashboard.py#L740), so I guess that’s why I missed this.

Still, I wonder if there’s a better way to solve this than having a hardcoded list of humanitarian codes? Seems like we could easily forget to update this in the future…

**Comment by markbrough** [comment]
Hmm this is a good question. Perhaps we could assume that any codes matching the pattern `72xxx`, `73xxx` or `74xxx` are humanitarian?
