### ISSUE TITLE
GitHub actions deploy happens for all branches

### ISSUE THREAD

**Issue by Bjwebb** [codeforIATI/IATI-Stats#25]
Deploy to [IATI-Stats-Public](https://github.com/OpenDataServices/IATI-Stats-public) gh-pages branch happens for any branch pushed to this repository. This would include branches that aren't ready to go live yet.

https://github.com/codeforIATI/IATI-Stats/blob/d32487f3e51673b09e6e6127848b6164b8b030e7/.github/workflows/run.yml#L74-L83

**Comment by andylolz** [comment]
Yeah, that’s a good point. [Analytics does the right thing](https://github.com/codeforIATI/analytics/blob/3c2b04d8199435294b651952fcb5d4afe3104190/.github/workflows/build.yml#L2-L8), but this repo doesn’t.

**Comment by andylolz** [comment]
Should hopefully be fixed now (by never building on push).

**Comment by andylolz** [comment]
If it’s useful @Bjwebb we could set up codeforIATI/IATI-Stats-dev – equivalent to [codeforIATI/analytics-dev](https://github.com/codeforIATI/analytics-dev).

I haven’t had a use for that yet, but it probably makes sense for it to exist.

**Comment by Bjwebb** [comment]
Yes, that would be useful for my current work, for which I need to test how much longer the stats run takes.

**Comment by andylolz** [comment]
Okay cool, \*hopefully\* that should be sorted…

So if you push to `dev`, it _should_ build to https://github.com/codeforIATI/IATI-Stats-dev

**Comment by andylolz** [comment]
Oh, boring – I did it a bit wrong https://github.com/codeforIATI/IATI-Stats/actions/runs/3095964959/jobs/5010962980

**Comment by Bjwebb** [comment]
I had a go at disabling gitaggregate to see if everything else works.

**Comment by andylolz** [comment]
Cool cool, sounds good.

**Comment by Bjwebb** [comment]
Yes, it works. Thanks for setting this up.
